config/routes.rb
BitcoinBank::Application.routes.draw do
  resources :invoices, :only => [:index, :new, :create, :show, :destroy]

  resource :user, :only => [:edit, :update] do
    get :ga_otp_configuration
    post :reset_ga_otp_secret
    put :update_password
    get :edit_password

    resources :yubikeys, :only => [:index, :create, :destroy]
    resources :bank_accounts, :only => [:index, :create, :destroy]
    resources :tickets do
      resources :comments, :only => :create
      member do
        post :close
        post :reopen
        post :solve
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # These routes need some loving :/
  resource :chart, :path => "charts", :only => [] do
    get :price
  end

  resource :account, :only => [:show] do
    match '/balance/:currency',
      :action => 'balance',
      :as => 'balance',
      :only => :get
      
    resources :transfers, :only => [:index, :new, :create, :show] 
    
    #get :deposit
    resources :deposits, :only => [:new, :create, :show, :destroy, :update] 
    
    resources :trades, 
      :only => [:index]
    
    resources :invoices

    resources :trade_orders, :only => [:index, :new, :create, :destroy] do
      post :activate
    end
  end

  match "/s/:name" => "static_pages#show", :as => :static
  
  match '/third_party_callbacks/:action',
    :controller => :third_party_callbacks

  namespace :admin do
    %w{ announcements yubikeys static_pages currencies tickets comments }.each { |r| resources(r.to_sym) {as_routes} }

    resources :pending_transfers do
      as_routes
      
      member do
        post :process_tx, :cancel_tx
      end
    end
    
    resources :users do
      as_routes
      
      member do
        get :balances
      end
      
      resources :account_operations do
        as_routes
      end
    end
    
    match '/balances', :to => 'informations#balances', :as => :balances
  end
  
  match '/qrcode/:data.png' => 'qrcodes#show', :as => :qrcode
  
  match '/order_book' => 'trade_orders#book'

  match '/trades' => 'trades#all_trades'

  match '/ticker' => 'trades#ticker'

  match '/economy' => 'informations#economy', :as => :economy

  match '/support' => 'informations#support', :as => :support

  root :to => 'informations#welcome'
end

app/controllers/admin/informations_controller.rb
class Admin::InformationsController < Admin::AdminController
  def balances
    @balances = [:brl, :btc].inject({}) do |balances, currency|
      balances[currency] = {}
      
      balances[currency][:user] = AccountOperation.
        joins(:account).
        where("`accounts`.`type` IN ('User', 'Manager', 'Admin')").
        with_currency(currency).
        select("SUM(`amount`) AS `amount`").
        first.
        amount
     
      balances[currency][:user] ||= 0
      
      balances[currency][:reported] = reported_balance(currency)
      
      if balances[currency][:reported].is_a? Numeric
        balances[currency][:delta] = balances[currency][:reported] - balances[currency][:user]
      else
        balances[currency][:delta] = "N/A"
      end
      
      balances
    end
    
    @balance_currencies = @balances.keys.map(&:to_s).sort.map(&:to_sym)
    
  end
  
  
  protected
    
    def reported_balance(currency)
      if currency == :btc
        Bitcoin::Client.instance.get_balance
      elsif [:lreur, :lrusd].include?(currency)
        #LibertyReserve::Client.instance.get_balance(currency)
      else
        "N/A"
      end
    end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  skip_before_filter :authenticate_user!

  def welcome
    currency = (params[:currency] || "brl").downcase.to_sym
    
    @min_y = [0.3 * (Trade.last_week.with_currency(currency).minimum(:ppc) or 0) - (Trade.with_currency(currency).maximum(:ppc) or 0), 0].max
    @max_y = 1.3 * (Trade.last_week.with_currency(currency).maximum(:ppc) or 0)

    @max_x = DateTime.now
    @min_x = @max_x.advance(:days => -7)

    @series = []
    @options = jqchart_defaults

    @options[:series] << {
      :label => currency.to_s.upcase,
      :color => color_for_currency(currency)
    }
    
    @options[:axes][:yaxis][:min] = @min_y
    @options[:axes][:yaxis][:max] = @max_y

    @options[:axes][:xaxis][:min] = @min_x.strftime("%Y-%m-%d %H:%M:%S")
    @options[:axes][:xaxis][:max] = @max_x.strftime("%Y-%m-%d %H:%M:%S")

    line = Trade.plottable(currency).map do |trade|
      [trade.created_at.strftime("%Y-%m-%d %H:%M:%S"), trade.ppc]
    end

    unless line.blank?
      line << [@max_x.strftime("%Y-%m-%d %H:%M:%S"), line.last[1]]
    end

    @series << line
  end

  def jqchart_defaults
    {
      :legend => {
        :show => true
      },
      :axes => {
        :yaxis => {
          :tickOptions => {
            :formatString => "%.4f"
          }
        },
        :xaxis => {
          :tickOptions => {
            :formatString => (t :chart_date_format)
          },
          :tickInterval => "1 day"
        }
      },
      :highlighter => {
				:show => true,
        :tooltipAxes => 'y',
        :showMarker => true
		  },
      :series => [
      ]
    }
  end

  def support
    if current_user
      @tickets = current_user.tickets
    end
  end
  
  
  protected

  def color_for_currency(currency)
    colors = {
      :lrusd => "#068300",
      :lreur => "#0E00C1",       
      :eur => "#AFAAF3",
      :cad => "#6db7e1",
      :inr => "#c40f75",
      :pgau => "#b58f24" 
    }
    
    colors[currency]
  end
end

app/helpers/admin/informations_helper.rb
module Admin::InformationsHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/_what_is_bitcoin.de.html.erb
<h2>Was ist Bitcoin?</h2>
<p>
  Bitcoin ist eine digitale Peer-to-Peer Währung. Peer-to-Peer bedeutet, dass es keine zentrale
  Authorität gibt die neues Geld ausgibt oder Transaktionen überwacht. Stattdessen werden diese
  Aufgaben gemeinsam durch die Teilnehmer des Netzwerks durchgeführt.
  Das hat folgende Vorteile:
<ul>
  <li>
	Bitcoins können einfach über das Internet verschickt werden ohne Dienstleistern vertrauen
	zu müssen.
  </li>
  <li>
	Transaktionen können nicht widerrufen werden.
  </li>
  <li>
	Sie sind sicher vor möglichen Krisen, die durch das partielle Reservesystem und
	Zentralbanken verursacht werden können. Die begrenzte Steigerung der Geldmenge im Bitcoin-System
	wird gerecht (nach Leistung des Prozessors) auf das  Netzwerk verteilt und nicht nur
	durch Banken.
  </li>
</ul>
Weitere Erläuterungen können sie auf <strong><%= link_to "bitcoin.org", "http://bitcoin.org" %></strong> finden.
</p>

app/views/informations/_what_is_bitcoin.en.html.erb
<h2>What is Bitcoin?</h2>
<p>Bitcoin is a peer-to-peer, open source, digital currency:</p>
<ul>
<li>Bitcoins can be sent easily through the Internet,</li>
<li>Transactions are irreversible,</li>
<li>They are safe from uncontrolled inflation</li>
</ul>
<p>Read more at <a href="http://bitcoin.org/en/">Bitcoin.org</a></p>
<h2>Bitfication Support</h2>
<p>If you have any problems or suggestions, please, send an e-mail to: <a href="mailto:support@bitfication.com">Bitfication Support</a></p>

app/views/informations/_what_is_bitcoin.fr.html.erb
<h2>Que sont les Bitcoins ?</h2>
<p>
  Bitcoin est une monnaie électronique décentralisée. Il n'y a pas d'autorité central régulant la monnaie, son émission et le suivi des transactions sont gérées collectivement par tous les noeuds du réseau. Avantages :
<ul>
  <li>
    Les bitcoins peuvent-être transférés facilement via Internet, sans intermédiaire.
  </li>
  <li>
    Les transactions sont irréversibles.
  </li>
  <li>
    Il n'y a pas d'insécurité monétaire causée par l'émission de monnaie par les banques centrales. L'inflation limitée et bornée de la masse monétaire est distribuée à travers tout le réseau et non monopolisée par le système bancaire.
  </li>
</ul>
Plus d'informations : <strong><%= link_to "bitcoin.org", "http://bitcoin.org" %></strong>.
</p>

app/views/informations/_what_is_bitcoin.pt.html.erb
<h2>O que é o Bitcoin?</h2>
<p>Bitcoin é a primeira moeda digital P2P e de código aberto (Bitcoin é um Software Livre):</p>
<ul>
  <li>Os Bitcoins podem ser enviados diretamente pela Internet,</li>
  <li>As transações de Bitcoins são irreversíveis,</li>
  <li>São seguros contra inflação descontrolada</li>
</ul>
Maiores detalhes em: <strong><%= link_to "Bitcoin.org", "http://bitcoin.org/pt/" %></strong>.
</p>
<h2>Suporte Bitfication</h2>
<p>Se você está enfrentando algum problema ou tem sugestões, por favor, envie um e-mail para: <a href="mailto:support@bitfication.com">Suporte Bitfication</a></p>

app/views/informations/economy.html.erb
<h1><%= t :economy_title %></h1>
<h2><%= t :how_many_generated %></h2>
<p><%= t :generated_coins_html, :count=>(number_to_currency (Bitcoin::Client.instance.get_block_count * 50), :precision => 8, :unit => '') %></p>

app/views/informations/faq.html.erb
<div id="faq">
  <h1><%= t :faq_title %></h1>
  <div class="question">
    <%= render :partial => "what_is_bitcoin" %>
  </div>
</div>

app/views/informations/support.html.haml
%h1= t(".contact")
%p= t(".contact_description_html", :email => "support@bitfication.com")

%h1= t("activerecord.models.ticket.other")

- if current_user
  %p
    = t(".your_tickets", :count => @tickets.pending.count)
  %p
    = link_to t(".open_a_ticket"), new_user_ticket_path
    - unless @tickets.blank?
      = " | "
      = link_to t(".view_tickets"), user_tickets_path

- else
  = t(".please_sign_in")

app/views/informations/welcome.html.haml
<div id="fb-root"></div>
<script>(function(d, s, id)
{
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id))
{
return;
}
js = d.createElement(s);
js.id = id;js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

%div{ :id => "price-chart-container", :class => "chart-container" }
  %h3= t ".trading_data_title"
  %div{ :id => "price-chart", :class => "chart", :style => "margin:auto;margin-top:2em;width:400px;height:300px" }
    - if Trade.count < 1
      = t(".chart_notrades")
      
  %br
  = form_tag root_path, :method => :get do
    %select{ :name => "currency", :onchange => "$(this).parents('form').submit()", :style => "float:right" }

      - Currency.all.map(&:code).reject{ |c| c == "BTC"}.sort.each do |c|
        - if ((params[:currency].blank? && c == "BRL") || params[:currency] == c)
          %option{ :selected => "selected".html_safe, :value => c }
            = t("activerecord.extra.currency.codes.#{c.downcase}")
            = c.upcase
        - else
          %option{ :value => c }
            = t("activerecord.extra.currency.codes.#{c.downcase}")
            = c.upcase

%script{ :src => "//platform.twitter.com/widgets.js", :type => "text/javascript"}

%h1= t ".welcome"
%div{ :class => "question", :style => "text-align:justify" }
  = render :partial => "what_is_bitcoin"

%div{ :class => "question", :style => "text-align:justify" }
  %h2= t(".download")
  %ul{ :id => "downloads" }
    %li= link_to image_tag("os/linux.png") + "Linux", "http://sourceforge.net/projects/bitcoin/files/Bitcoin/bitcoin-0.8.6/bitcoin-0.8.6-linux.tar.gz/download"
    %li= link_to image_tag("os/ubuntu_ppa.png") + "Ubuntu PPA", "https://launchpad.net/~bitcoin/+archive/bitcoin"
    %li= link_to image_tag("os/apple.png") + "Mac OS X", "http://sourceforge.net/projects/bitcoin/files/Bitcoin/bitcoin-0.8.6/bitcoin-0.8.6-macosx.dmg/download"
    %li= link_to image_tag("os/windows.png") + "Windows", "http://sourceforge.net/projects/bitcoin/files/Bitcoin/bitcoin-0.8.6/bitcoin-0.8.6-win32-setup.exe/download"
    %li= link_to image_tag("os/github.png") + t(".source"), "https://github.com/bitcoin/bitcoin", :target => "_blank"

%script{ :type => "text/javascript" }
  options =
  = @options.to_json.html_safe;
  options.axes.xaxis.renderer = $.jqplot.DateAxisRenderer;

  $.jqplot('price-chart',
  = @series.to_json.html_safe
  , options)



%ul{ :id => "social-buttons" }
  %li
    %a{ :href => "https://twitter.com/Bitfication", :class => "twitter-follow-button"}
      Follow @Bitfication
  %li
    %div{ :class => "fb-like", :"data-href" => "https://www.facebook.com/Bitfication?skip_nax_wizard=true", :"data-send" => "true", :"data-width" => "450", :"data-show-faces" => "true" }