config/routes.rb
BitcoinBank::Application.routes.draw do
  resources :invoices, :only => [:index, :new, :create, :show, :destroy]

  resource :user, :only => [:edit, :update] do
    get :ga_otp_configuration
    post :reset_ga_otp_secret
    put :update_password
    get :edit_password

    resources :yubikeys, :only => [:index, :create, :destroy]
    resources :bank_accounts, :only => [:index, :create, :destroy]
    resources :tickets do
      resources :comments, :only => :create
      member do
        post :close
        post :reopen
        post :solve
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # These routes need some loving :/
  resource :chart, :path => "charts", :only => [] do
    get :price
  end

  resource :account, :only => [:show] do
    match '/balance/:currency',
      :action => 'balance',
      :as => 'balance',
      :only => :get
      
    resources :transfers, :only => [:index, :new, :create, :show] 
    
    #get :deposit
    resources :deposits, :only => [:new, :create, :show, :destroy, :update] 
    
    resources :trades, 
      :only => [:index]
    
    resources :invoices

    resources :trade_orders, :only => [:index, :new, :create, :destroy] do
      post :activate
    end
  end

  match "/s/:name" => "static_pages#show", :as => :static
  
  match '/third_party_callbacks/:action',
    :controller => :third_party_callbacks

  namespace :admin do
    %w{ announcements yubikeys static_pages currencies tickets comments }.each { |r| resources(r.to_sym) {as_routes} }

    resources :pending_transfers do
      as_routes
      
      member do
        post :process_tx, :cancel_tx
      end
    end
    
    resources :users do
      as_routes
      
      member do
        get :balances
      end
      
      resources :account_operations do
        as_routes
      end
    end
    
    match '/balances', :to => 'informations#balances', :as => :balances
  end
  
  match '/qrcode/:data.png' => 'qrcodes#show', :as => :qrcode
  
  match '/order_book' => 'trade_orders#book'

  match '/trades' => 'trades#all_trades'

  match '/ticker' => 'trades#ticker'

  match '/economy' => 'informations#economy', :as => :economy

  match '/support' => 'informations#support', :as => :support

  root :to => 'informations#welcome'
end

app/models/deposit.rb
class Deposit < AccountOperation 
  include ActionView::Helpers::NumberHelper
  include ActiveRecord::Transitions
  
  DEPOSIT_COMMISSION_RATE = BigDecimal("0.01")
  
  attr_accessible :bank_account_id, :bank_account_attributes

  belongs_to :account
  
  #accepts_nested_attributes_for :bank_account
  
  #before_validation :check_bank_account_id

  validates :currency,
    :inclusion => { :in => ["BRL"] }
  
  validates :amount,
    :numericality => true,
    :minimal_amount => true
    #:negative => false

=begin  
  state_machine do
    state :pending
    state :processed
    state :cancelled
    
    event :process do
      transitions :to => :processed,
        :from => :pending
    end
    
    event :cancel do
      transitions :to => :cancelled,
        :from => :pending
    end
    
  end
=end

  def self.from_params(params)
    deposit = class_for_transfer(params[:currency]).new(params)
   
    if deposit.amount
      deposit.amount = deposit.amount.abs 
    end
    
    deposit
  end
  
  def self.class_for_transfer(currency)
    currency = currency.to_s.downcase.to_sym
    self
  end
  
  def execute
    
    raise 'executing'
    
  end

  def check_bank_account_id
    if bank_account_id && account.bank_accounts.find(bank_account_id).blank?
      raise "Someone is trying to pull something fishy off"
    end
  end
  
  
  
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  include DepositsHelper
  
  DEPOSIT_COMMISSION_RATE = BigDecimal("0.01")
  
  respond_to :html, :json
  
  def new
    
    @bank_account = BankAccount.new
    
    #debugger
    
    @currencies_deposit = Currency.where('code != ?', "btc")
    
    @deposit_rate = DEPOSIT_COMMISSION_RATE
    
    @pending_deposits = Deposit.where(:account_id => current_user.id, :state => "pending")
    
    #default currency
    if params[:currency].nil?
      currency = "BRL"
    else
      currency = params[:currency]
    end
    
    if ["BRL"].include? currency
      @deposit = Deposit.new(:currency => params[:currency])
    end
    
    get_deposit_account
    
  end
  
  def create
    
    @bank_account = BankAccount.new
    
    @currencies_deposit = Currency.where('code != ?', "btc")
    
    @deposit_rate = DEPOSIT_COMMISSION_RATE
    
    @pending_deposits = Deposit.where(:account_id => current_user.id, :state => "pending")
    
    @deposit = Deposit.from_params(params[:deposit])
    
    @deposit.account = current_user
    
    @account_id = current_user.name
    
    # Calculate fee for deposits
    deposit_fee = @deposit.amount * DEPOSIT_COMMISSION_RATE
      
    storage_amount = @deposit.amount
    
    @deposit.amount = @deposit.amount - deposit_fee
    
    Operation.transaction do

      o = Operation.create!
      o.account_operations << @deposit
      
      o.account_operations << AccountOperation.new do |ao|
        ao.amount = (storage_amount * -1)
        ao.currency = @deposit.currency
        ao.account = Account.storage_account_for(@deposit.currency)
      end
      
      # Charge a fee for depoists
      o.account_operations << AccountOperation.new do |fee|
        fee.currency = @deposit.currency
        fee.amount = deposit_fee
        fee.account = Account.storage_account_for(:fees)
      end
           
      raise(ActiveRecord::Rollback) unless o.save
    end
    
    unless @deposit.new_record?
      
      get_deposit_account
      
      calc_before_after_fee(@deposit)
      
      @user = current_user
      
      # dispatch email to user
      UserMailer.deposit_request_notification(@deposit).deliver
      
      respond_with do |format|
        format.html { render :action => "show" }
        format.json { render :json => @deposit }
      end
    else
      render :action => :new
    end
  end
  
  def show
    
    @deposit = Deposit.find(params[:id])
    
    calc_before_after_fee(@deposit)
    
    get_deposit_account
    
    @user = current_user
    
  end
  
  def destroy
    
    Deposit.where(:id => params[:id], :account_id => current_user.id).first.destroy

    redirect_to new_account_deposit_path,
      :notice => t(".deposits.destroy.deposit_deleted")
  end
  
  def update
    deposit = Deposit.where(:id => params[:id], :account_id => current_user.id).first
    
    deposit.attachment = params[:deposit][:attachment]
    
    if deposit.save
      redirect_to account_deposit_path,
      :notice => t(".deposits.update.deposit_file_added")
    else
      redirect_to account_deposit_path,
      :notice => t(".deposits.update.error")
    end
    
  end
  
  protected
  
  def fetch_bank_accounts
    @bank_accounts = current_user.bank_accounts.map { |ba| [ba.bank_name + " : " + ba.ag + " / " + ba.cc, ba.id] }
  end
  
  def calc_before_after_fee(deposit)
    
    @deposit_beforefee = '%.0f' % (deposit.amount * (1 + DEPOSIT_COMMISSION_RATE)) 
    
    @deposit_afterfee =  '%.0f' % deposit.amount
    
  end
  
end

app/helpers/deposits_helper.rb
module DepositsHelper
  def color_for(deposit)
    deposit.amount > 0 ? (deposit.confirmed? ? "green" : "unconfirmed") : "red"
  end

  def confirmation_tooltip_for(deposit)
    unless deposit.confirmed?
      t :confirmations_left, :count => (Transfer::MIN_BTC_CONFIRMATIONS - deposit.bt_tx_confirmations)
    end
  end
  
  def deposit_details(deposit)
    link_to(image_tag("details.png", :alt => t(".details"), :title => t(".details")), account_deposit_path(deposit))
  end
  
  def deposit_state(state, options = {})   
    content_tag :span,
      :class => ["deposit-state", color_for_deposit_state(state)] do
      "#{options[:icon] ? image_tag("#{state}.png", :class => "state-icon") : ""} #{options[:message]}".strip.html_safe
    end
  end
  
  def color_for_deposit_state(state)
    case state 
    when "pending"
      "orange"
    when "processed"
      "green"
    end
  end
  
  def get_deposit_account
    bank_account = YAML::load(File.open(File.join(Rails.root, "config", "banks.yml")))
    
    if bank_account
      bank_account = bank_account[Rails.env]
      @ag = bank_account["ag"]
      @cc = bank_account["cc"]
      @cnpj = bank_account["cnpj"]
      @bic = bank_account["bic"]
      @iban = bank_account["iban"]
      @bank = bank_account["bank"]
      @bank_address = bank_account["bank_address"]
      @account_holder = bank_account["account_holder"]
      @account_holder_address = bank_account["account_holder_address"]
    end
    
    #@user = current_user
    
  end
end

app/views/deposits/_bankinfo.html.haml
%div{:style => "padding: 5px 5px 5px 5px;"}
  = t("accounts.deposit.deposit_eur_body_html", :account_id => @user.name)
%div#bank-info{:style => "white-space: normal;"}
  %table
    %tr
      %th= t("accounts.deposit.comment")
      %td= @user.name
    %tr
      %th= t("accounts.deposit.account_holder")
      %td.account-holder= @account_holder
    %tr
      %th
      %td.account-holder-address= @account_holder_address
    %tr
      %td{ :colspan => 2 } &nbsp;
    %tr
      %th= t("accounts.deposit.ag")
      %td= @ag
    %tr
      %th= t("accounts.deposit.cc")
      %td= @cc
    %tr
      %th= t("accounts.deposit.cnpj")
      %td= @cnpj
    %tr
      %th= t("accounts.deposit.bank")
      %td.bank= @bank
    %tr
      %th
      %td.bank-address= @bank_address

app/views/deposits/_bankinfo.text.haml
= t("accounts.deposit.deposit_eur_body_html", :account_id => @user.name)

= t("accounts.deposit.comment")
= @user.name

= t("accounts.deposit.account_holder")
= @account_holder
= @account_holder_address

= t("accounts.deposit.ag")
= @ag

= t("accounts.deposit.cc")
= @cc

= t("accounts.deposit.cnpj")
= @cnpj

= t("accounts.deposit.bank")
= @bank
= @bank_address

app/views/deposits/index.html.haml
%h1= t :account_history_title

%table#history.default
  %tr
    %th Date
    %th= t :currency
    %th= t :amount
    %th.auto-sized

  - unless @deposits.blank?
    - @deposits.each do |deposit|
      %tr{ :class => cycle('even', 'odd') }
        %td= l deposit.created_at
        %td
          = currency_icon_for(deposit.currency)
          = deposit.currency
        %td.amount
          %span{ :class => color_for(deposit), :title => confirmation_tooltip_for(deposit) }
            = "#{deposit.amount > 0 ? "+" : "-"} #{number_to_currency deposit.amount.abs, :unit => "", :precision => 8}"
        %td.auto-sized
          = deposit_details(deposit)  

  - else
    = render :partial => "layouts/no_data"

= will_paginate(@deposits)

app/views/deposits/new.html.haml
%h1= t(".bitcoins.title")
%div{:style => "float:left; width: 50%" }
  %div{:style => "line-height: 30pt;" }
    %p
      %strong= t(".bitcoins.address") + ":"
      = link_to @current_user.bitcoin_address, "bitcoin:#{@current_user.bitcoin_address}"
    %p
      %strong= t(".bitcoins.conf_rqd") + ":"
      = Transfer::MIN_BTC_CONFIRMATIONS
      = t(".bitcoins.conf_rqd_unit")
    %p
      %strong= t(".bitcoins.conf_time") + ":"
      = Transfer::MIN_BTC_CONFIRMATIONS * 10
      = t(".bitcoins.conf_time_unit")
  %p
    = t(".bitcoins.add_info_html", :tx_address => "http://blockchain.info/address/#{@current_user.bitcoin_address}")

%div{:style => "float:left" }
  = image_tag(qrcode_image_path(current_user.bitcoin_address), :size => "120x120")
%div{:style => "clear:both;" }
%h1= t(".deposit_eur_title")

%p= t(".deposit_form")

%br
= form_for @deposit, :as => :deposit, :url => account_deposits_path do |f|
  = errors_for(@deposit, :translated_message => t(".error"), :include_nested => :bank_account)
  
  .form-field
    = f.label :currency
    = f.select :currency, options_from_collection_for_select(@currencies_deposit, 'code', I18n.locale, @deposit.currency)
    -

  .form-field
    = f.label :amount
    = f.text_field :amount, :value => (@deposit.amount)? "100" : @deposit.amount, :autocomplete => "off"
  
  .form-field
    = f.submit :value => t(".submit"), :class => "submit"
%br

- if @pending_deposits.count > 0
  %h1= t(".deposit_pendings")
  
  %table{:class=>"default"}
    %thead
      %tr
        %th=t("activerecord.attributes.transfer.id")
        %th=t("activerecord.attributes.transfer.created_at")
        %th=t("activerecord.attributes.transfer.amount_afterfee")
        %th=t("activerecord.attributes.transfer.amount_tosend")
        %th=t("activerecord.attributes.transfer.currency")
        %th=t("activerecord.attributes.transfer.fast_deposit")
        %th.auto-sized
    %tbody
      - @pending_deposits.each do |d|
        %tr{ :class => cycle('even', 'odd') }
          %td.amount=link_to d.id, account_deposit_path(d.id)
          %td=d.created_at
          %td.amount=number_to_currency(d.deposit_after_fee, unit: "", separator: ".", delimiter: ",", precision: 3)
          %td.amount=number_to_currency(d.deposit_before_fee, unit: "", separator: ".", delimiter: ",", precision: 3)
          %td.auto-sized=currency_icon_for(d.currency)
          %td.auto-sized
            - if d.attachment? 
              = image_tag "processed.png"
          %td.auto-sized=tf_delete_link_for(d)
      

  

app/views/deposits/show.html.haml
%h1
  Deposit no.
  %span.fixed= @deposit.id

%table.default.details
  %tr
    %th= t("activerecord.attributes.transfer.id")
    %td.fixed= @deposit.id

  %tr
    %th= t("activerecord.attributes.transfer.created_at")
    %td= l(@deposit.created_at)

  %tr
    %th= t("activerecord.attributes.transfer.state")
    %td= transfer_state(@deposit.state, :message => t(".state.#{@deposit.state}").html_safe, :icon => true)

  -#%tr
    %th= t("activerecord.attributes.transfer.amount_afterfee")
    %td.fixed= number_to_currency(@deposit_afterfee, :unit => "", :precision => 3)
    
  %tr
    %th= t("activerecord.attributes.transfer.amount_tosend")
    %td.fixed= number_to_currency(@deposit_beforefee, :unit => "", :precision => 3)

  %tr
    %th= t("activerecord.attributes.transfer.currency")
    %td
      = currency_icon_for(@deposit.currency)
      = @deposit.currency

  - unless @deposit.comment.blank?
    %tr
      %th= t("activerecord.attributes.transfer.comment")
      %td
        %pre= @deposit.comment 

- # form for file upload
%h1=t("accounts.deposit.fast_deposit")

- if @deposit.attachment?
  #uploadedbox{:style=> "width: 100%;"}
    #ubimg{:style => "float: left;"}
      = image_tag "processed.png"
    #ubtext{:style=> "float: right; width: 97%; font-weight: bold; color: green;"}
      %p= t("accounts.deposit.fast_deposit_uploaded")
- else
  %p= t("accounts.deposit.fast_deposit_notice_html")
  
  = form_for @deposit, :as => :deposit, :url => account_deposit_path(@deposit), :html => { :multipart => true } do |f|
    %p
      = f.file_field :attachment
    %p
      = f.submit :value => t(".submit"), :class => "submit"

#clear{:style => "clear:both;"}

%h1=t("accounts.deposit.deposit_eur_title")
= render :partial => 'bankinfo'