config/routes.rb
BitcoinBank::Application.routes.draw do
  resources :invoices, :only => [:index, :new, :create, :show, :destroy]

  resource :user, :only => [:edit, :update] do
    get :ga_otp_configuration
    post :reset_ga_otp_secret
    put :update_password
    get :edit_password

    resources :yubikeys, :only => [:index, :create, :destroy]
    resources :bank_accounts, :only => [:index, :create, :destroy]
    resources :tickets do
      resources :comments, :only => :create
      member do
        post :close
        post :reopen
        post :solve
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # These routes need some loving :/
  resource :chart, :path => "charts", :only => [] do
    get :price
  end

  resource :account, :only => [:show] do
    match '/balance/:currency',
      :action => 'balance',
      :as => 'balance',
      :only => :get
      
    resources :transfers, :only => [:index, :new, :create, :show] 
    
    #get :deposit
    resources :deposits, :only => [:new, :create, :show, :destroy, :update] 
    
    resources :trades, 
      :only => [:index]
    
    resources :invoices

    resources :trade_orders, :only => [:index, :new, :create, :destroy] do
      post :activate
    end
  end

  match "/s/:name" => "static_pages#show", :as => :static
  
  match '/third_party_callbacks/:action',
    :controller => :third_party_callbacks

  namespace :admin do
    %w{ announcements yubikeys static_pages currencies tickets comments }.each { |r| resources(r.to_sym) {as_routes} }

    resources :pending_transfers do
      as_routes
      
      member do
        post :process_tx, :cancel_tx
      end
    end
    
    resources :users do
      as_routes
      
      member do
        get :balances
      end
      
      resources :account_operations do
        as_routes
      end
    end
    
    match '/balances', :to => 'informations#balances', :as => :balances
  end
  
  match '/qrcode/:data.png' => 'qrcodes#show', :as => :qrcode
  
  match '/order_book' => 'trade_orders#book'

  match '/trades' => 'trades#all_trades'

  match '/ticker' => 'trades#ticker'

  match '/economy' => 'informations#economy', :as => :economy

  match '/support' => 'informations#support', :as => :support

  root :to => 'informations#welcome'
end

app/models/transfer.rb
class Transfer < AccountOperation
  include ActiveRecord::Transitions
  
  DEPOSIT_WITHDRAW_COMMISSION_RATE = BigDecimal("0.01")
  
  before_validation :round_amount,
    :on => :create  
  
  after_create :execute

  validates :amount,
    :numericality => true,
    :user_balance => true,
    :minimal_amount => true,
    :maximal_amount => true,
    :negative => true

  validates :currency,
    :inclusion => { :in => ["BRL", "BTC"] }

  def type_name
    type.gsub(/Transfer$/, "").underscore.gsub(/\_/, " ").titleize
  end

=begin
  state_machine do
    state :pending
    state :processed

    event :process do
      transitions :to => :processed,
        :from => :pending
    end
  end
=end

  # all transfers are withdrawals
  def self.from_params(params)
    transfer = class_for_transfer(params[:currency]).new(params)
   
    if transfer.amount
      transfer.amount = -transfer.amount.abs 
    end
    
    transfer
  end

  def round_amount
    unless amount.nil? || amount.zero?
      self.amount = self.class.round_amount(amount, currency)
    end
  end

  def self.minimal_amount_for(currency, display)
    currency = currency.to_s.downcase.to_sym

    #if [:u, :lreur].include?(currency)
    #  BigDecimal("0.02")
    #if currency == :usd
    #  BigDecimal("100.0")
    
    if currency == :brl
      if display==true
        BigDecimal("100.0")
      else
        BigDecimal("100.0")*(1-DEPOSIT_WITHDRAW_COMMISSION_RATE)
      end
    elsif currency == :btc
      BigDecimal("0.01")
    else
      raise RuntimeError.new("Invalid currency")
    end
  end  

  def self.round_amount(amount, currency)
    currency = currency.to_s.downcase.to_sym
    amount = amount.to_f if amount.is_a?(Fixnum)
    amount.to_d.round(8, BigDecimal::ROUND_DOWN)
  end
  
  def self.class_for_transfer(currency)
    
    puts currency
    
    currency = currency.to_s.downcase.to_sym

    #if [:usd, :brl].include?(currency)
    if [:brl].include?(currency)
      WireTransfer
    #elsif [:lrusd, :lreur].include?(currency)
    #  LibertyReserveTransfer
    elsif currency == :btc
      BitcoinTransfer
    else
      raise RuntimeError.new("Invalid currency")
    end
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  WITHDRAWAL_COMMISSION_RATE = BigDecimal("0.01")
  
  respond_to :html, :json
  
  def index
    
    @transfers = current_user.account_operations.paginate(:page => params[:page], :per_page => 16)
    respond_with @transfers
  end

  def new
    
    @withdrawal_rate = WITHDRAWAL_COMMISSION_RATE
    
    if ["BRL", "USD"].include? params[:currency]
      @transfer = WireTransfer.new(:currency => params[:currency])
      @transfer.build_bank_account
      fetch_bank_accounts
    else 
      # default currency
      if params[:currency].nil?
        @transfer = Transfer.new(:currency => "BTC")
      else
        @transfer = Transfer.new(:currency => params[:currency])
      end
    end
    
  end
  
  def show
    @transfer = current_user.account_operations.find(params[:id])
    respond_with @transfer
  end
  
  def create
    
    @withdrawal_rate = WITHDRAWAL_COMMISSION_RATE
    
    # reset max (to avoid rounding errors)
    if params[:transfer][:amount] == '%.2f' % current_user.max_withdraw_for(params[:transfer][:currency])
      
      params[:transfer][:amount] = current_user.max_withdraw_for(params[:transfer][:currency])
      
    end
    
    @transfer = Transfer.from_params(params[:transfer])
    
    @transfer.account = current_user
    
    if @transfer.is_a?(WireTransfer) && @transfer.bank_account
      @transfer.bank_account.user_id = current_user.id
      
      # Charge a fee for withdrawals
      withdrawal_fee = BigDecimal(params[:transfer][:amount]) * WITHDRAWAL_COMMISSION_RATE
      
      storage_amount = BigDecimal(params[:transfer][:amount]) - withdrawal_fee
      
    else
      
      storage_amount = BigDecimal(params[:transfer][:amount])
      
    end
    
    #debugger
    
    Operation.transaction do

      o = Operation.create!
      o.account_operations << @transfer
      
      o.account_operations << AccountOperation.new do |ao|
        ao.amount = storage_amount
        ao.currency = @transfer.currency
        ao.account = Account.storage_account_for(@transfer.currency)
      end
      
      # Charge a fee for withdrawals
      if @transfer.is_a?(WireTransfer) && @transfer.bank_account
        o.account_operations << AccountOperation.new do |fee|
          fee.currency = @transfer.currency
          fee.amount = withdrawal_fee
          fee.account = Account.storage_account_for(:fees)
        end
      end
      
      # link to pending transaction - to enable admin to cancel
      #p = PendingTransfer.new(:currency => @transfer.currency, :type => "WireTransfer", :state => "pending", :account => current_user.id, :op_btc => 1682, :op_brl => 1682, :op_fees => 1682)
      
      raise(ActiveRecord::Rollback) unless o.save
    end

    unless @transfer.new_record?
      respond_with do |format|
        format.html do
          redirect_to account_transfers_path,
            :notice => I18n.t("transfers.index.successful.#{@transfer.state}", :amount => @transfer.amount.abs, :currency => @transfer.currency)
        end
          
        format.json { render :json => @transfer }
      end
    else
      fetch_bank_accounts
      render :action => :new
    end
  end
  
  
  protected
  
  def fetch_bank_accounts
    @bank_accounts = current_user.bank_accounts.map { |ba| [ba.bank_name + " : " + ba.ag + " / " + ba.cc, ba.id] }
  end
end

app/helpers/transfers_helper.rb
module TransfersHelper
  def tf_delete_link_for(deposit)
    link_to image_tag("delete.png"),
      account_deposit_path(deposit),
      :method => :delete,
      :class => "delete",
      :confirm => t(".delete_deposit_confirm")
  end
  
  def color_for(transfer)
    transfer.amount > 0 ? (transfer.state=='cancelled'? "cancelled" : (transfer.confirmed? ? "green" : "unconfirmed")) : "red"
  end

  def confirmation_tooltip_for(transfer)
    unless transfer.confirmed?
      t :confirmations_left, :count => (Transfer::MIN_BTC_CONFIRMATIONS - transfer.bt_tx_confirmations)
    end
  end
  
  def transfer_details(transfer)
    link_to(image_tag("details.png", :alt => t(".details"), :title => t(".details")), account_transfer_path(transfer))
  end
  
  def transfer_state(state, options = {})   
    content_tag :span,
      :class => ["transfer-state", color_for_transfer_state(state)] do
      "#{options[:icon] ? image_tag("#{state}.png", :class => "state-icon") : ""} #{options[:message]}".strip.html_safe
    end
  end
  
  def color_for_transfer_state(state)
    case state 
    when "pending"
      "orange"
    when "processed"
      "green"
    when "cancelled"
      "red"
    end
  end
end

app/views/transfers/index.html.haml
%h1= t :account_history_title

%table#history.default
  %tr
    %th Date
    %th= t :currency
    %th= t :amount
    %th.auto-sized

  - unless @transfers.blank?
    - @transfers.each do |transfer|
      %tr{ :class => cycle('even', 'odd') }
        %td= l transfer.created_at
        %td
          = currency_icon_for(transfer.currency)
          = transfer.currency
        %td.amount
          %span{ :class => color_for(transfer), :title => confirmation_tooltip_for(transfer) }
            = "#{transfer.amount > 0 ? "+" : "-"} #{number_to_currency transfer.amount.abs, :unit => "", :precision => 8}"
        %td.auto-sized
          = transfer_details(transfer)  

  - else
    = render :partial => "layouts/no_data"

= will_paginate(@transfers)

app/views/transfers/new.html.haml
%h1= t(".title")
= t(".body_html")

%br

= form_for @transfer, :as => :transfer, :url => account_transfers_path do |f|
  = errors_for(@transfer, :translated_message => t(".error"), :include_nested => :bank_account)
  
  -# custom script to update 'will receive' & 'amount' boxes
  %script
    $(document).ready(function(e) {
    
    $('#transfer_amount').change(function() {
    
    var txtAmtval = $(this).val();
    
    $('#will_receive').val(txtAmtval * (1-#{@withdrawal_rate}));
        
    });
    
    $('#will_receive').change(function() {
    
    var txtAmtval = $(this).val();
    
    $('#transfer_amount').val(txtAmtval * (1+#{@withdrawal_rate}));
        
    });
    
    });
    
  .form-field
    = f.label :currency
    = f.select :currency, options_from_collection_for_select(@currencies, 'code', I18n.locale, @transfer.currency)
    - 
  - if @transfer.currency == "BTC"
    .form-field
      = f.label :address
      = f.text_field :address


  -#- if ["LRlUSD", "kLREUR"].include? @transfer.currency
  -#   .form-field
  -#     = f.label :lr_account_id
  -#     = f.text_field :lr_account_id

  - if ["BRL"].include? @transfer.currency
    - if @bank_accounts.blank? && @transfer.bank_account_id.blank?
      = f.fields_for :bank_account do |bank_account|
        = render :partial => 'bank_accounts/fieldsbr', :locals => { :form_builder => bank_account }
    - else
      .form-field
        = label_tag :bank_account_id, t(".bank_account")
        = f.select :bank_account_id, @bank_accounts, {}, { :prompt => "--" }
        .explanation= link_to t(".manage_bank_accounts"), user_bank_accounts_path
        
  .form-field
    = f.label :amount
    = f.text_field :amount, :value => (["BRL"].include? @transfer.currency)? '%.2f' % current_user.max_withdraw_for(@transfer.currency) : "100", :autocomplete => "off"

  - if ["BRL"].include? @transfer.currency
  
    .form-field
      = label_tag :will_receive, t(".will_receive")
      = text_field_tag :will_receive, '%.2f' % (current_user.max_withdraw_for(@transfer.currency)*(1-@withdrawal_rate))
    
  .form-field
    = f.submit :value => t(".submit"), :class => "submit"

app/views/transfers/show.html.haml
%h1
  Transaction no.
  %span.fixed= @transfer.id

%table.default.details
  %tr
    %th= t("activerecord.attributes.transfer.id")
    %td.fixed= @transfer.id

  %tr
    %th= t("activerecord.attributes.transfer.created_at")
    %td= l(@transfer.created_at)

  - if @transfer.is_a?(Transfer) | @transfer.is_a?(Deposit) 
    %tr
      %th= t("activerecord.attributes.transfer.state")
      %td= transfer_state(@transfer.state, :message => t(".state.#{@transfer.state}").html_safe, :icon => true)

  %tr
    %th= t("activerecord.attributes.transfer.amount")
    %td.fixed= number_to_currency(@transfer.amount, :unit => "", :precision => 8)

  %tr
    %th= t("activerecord.attributes.transfer.currency")
    %td
      = currency_icon_for(@transfer.currency)
      = @transfer.currency

  - if @transfer.bt_tx_id
    %tr
      %th= t("activerecord.attributes.transfer.bt_tx_id")
      %td.fixed= bbe_link(:tx, @transfer.bt_tx_id)

  - if @transfer.bt_tx_confirmations and @transfer.bt_tx_confirmations > 0
    %tr
      %th= t("activerecord.attributes.transfer.bt_tx_confirmations")
      %td.fixed= @transfer.bt_tx_confirmations

  - if @transfer.lr_transaction_id
    %tr
      %th= t("activerecord.attributes.transfer.lr_transaction_id")
      %td.fixed= @transfer.lr_transaction_id

  - if @transfer.px_tx_id
    %tr
      %th= t("activerecord.attributes.transfer.px_tx_id")
      %td.fixed= @transfer.px_tx_id

  - if @transfer.respond_to? :bank_account
    %tr
      %th= t("activerecord.attributes.bank_account.account_holder")
      %td.fixed= @transfer.bank_account.account_holder
    %tr
      %th= t("activerecord.attributes.bank_account.bank_name")
      %td.fixed= @transfer.bank_account.bank_name
    %tr
      %th= t("activerecord.attributes.bank_account.ag")
      %td.fixed= @transfer.bank_account.ag
    %tr
      %th= t("activerecord.attributes.bank_account.cc")
      %td.fixed= @transfer.bank_account.cc
    %tr
      %th= t("activerecord.attributes.bank_account.cnpj")
      %td.fixed= @transfer.bank_account.cnpj

  - unless @transfer.comment.blank?
    %tr
      %th= t("activerecord.attributes.transfer.comment")
      %td
        %pre= @transfer.comment