config/routes.rb
BitcoinBank::Application.routes.draw do
  resources :invoices, :only => [:index, :new, :create, :show, :destroy]

  resource :user, :only => [:edit, :update] do
    get :ga_otp_configuration
    post :reset_ga_otp_secret
    put :update_password
    get :edit_password

    resources :yubikeys, :only => [:index, :create, :destroy]
    resources :bank_accounts, :only => [:index, :create, :destroy]
    resources :tickets do
      resources :comments, :only => :create
      member do
        post :close
        post :reopen
        post :solve
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # These routes need some loving :/
  resource :chart, :path => "charts", :only => [] do
    get :price
  end

  resource :account, :only => [:show] do
    match '/balance/:currency',
      :action => 'balance',
      :as => 'balance',
      :only => :get
      
    resources :transfers, :only => [:index, :new, :create, :show] 
    
    #get :deposit
    resources :deposits, :only => [:new, :create, :show, :destroy, :update] 
    
    resources :trades, 
      :only => [:index]
    
    resources :invoices

    resources :trade_orders, :only => [:index, :new, :create, :destroy] do
      post :activate
    end
  end

  match "/s/:name" => "static_pages#show", :as => :static
  
  match '/third_party_callbacks/:action',
    :controller => :third_party_callbacks

  namespace :admin do
    %w{ announcements yubikeys static_pages currencies tickets comments }.each { |r| resources(r.to_sym) {as_routes} }

    resources :pending_transfers do
      as_routes
      
      member do
        post :process_tx, :cancel_tx
      end
    end
    
    resources :users do
      as_routes
      
      member do
        get :balances
      end
      
      resources :account_operations do
        as_routes
      end
    end
    
    match '/balances', :to => 'informations#balances', :as => :balances
  end
  
  match '/qrcode/:data.png' => 'qrcodes#show', :as => :qrcode
  
  match '/order_book' => 'trade_orders#book'

  match '/trades' => 'trades#all_trades'

  match '/ticker' => 'trades#ticker'

  match '/economy' => 'informations#economy', :as => :economy

  match '/support' => 'informations#support', :as => :support

  root :to => 'informations#welcome'
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :account_operations

  has_many :used_currencies,
    :dependent => :destroy
  
  belongs_to :parent,
    :class_name => 'Account'

  validates :name,
    :presence => true,
    :uniqueness => true

  # BigDecimal returned here
  def balance(currency, options = {} )
    account_operations.with_currency(currency).with_confirmations(options[:unconfirmed]).with_processed_active_deposits_only.map(&:amount).sum.round(5).abs
  end

  # Generates a new receiving address if it hasn't already been refreshed during the last hour
  def generate_new_address
    unless last_address_refresh && last_address_refresh > DateTime.now.advance(:hours => -1)
      self.last_address_refresh = DateTime.now
      self.bitcoin_address = Bitcoin::Client.instance.get_new_address(id.to_s)
      save
    end
  end

  def max_withdraw_for(currency)
    Transfer.round_amount(self.balance(currency), currency)
  end

  def self.storage_account_for(currency)
    account_name = "storage_for_#{currency.to_s.downcase}"
    account = find_by_name(account_name)

    if account
      account
    else
      Account.create! do |a|
        a.name = account_name
      end
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  respond_to :html, :json
  
  def show
    @balances = Currency.all.map(&:code).inject({}) do |acc, code|
      acc[code] = current_user.balance(code.downcase.to_sym)
      acc
    end
    
    @balances["ADDRESS"] = current_user.bitcoin_address
    @balances["UNCONFIRMED_BTC"] = current_user.balance(:btc, :unconfirmed => true) - current_user.balance(:btc)
    
    respond_with @balances
  end
  
  def balance
    @balance = {
      :balance => @current_user.balance(params[:currency]),
      :currency => params[:currency].upcase
    }
    
    if params[:currency] == 'btc'
      @balance[:unconfirmed] = current_user.balance(:btc, :unconfirmed => true) - current_user.balance(:btc)
    end
    
    respond_with @balance
  end
  
  def deposit
  end
  
#  def pecunix_deposit_form
#    @amount = params[:amount]
#    @payment_id = current_user.id
#    @config = YAML::load(File.read(File.join(Rails.root, "config", "pecunix.yml")))[Rails.env]
#    @hash = Digest::SHA1.hexdigest("#{@config['account']}:#{@amount}:GAU:#{@payment_id}:PAYEE:#{@config['secret']}").upcase
#  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def exact_balance(balance, code)
    "#{"%.5f" % balance} #{code.upcase}"
  end

  def color_for_balance(balance)
    if balance > 0
      "green"
    elsif balance < 0
      "red"
    end
  end

  def sign_for_balance(balance)
    if balance > 0
      "+"
    elsif balance < 0
      "-"
    end
  end
end

app/views/accounts/_balance_row.html.haml
- if (balance > 0) or %w{btc brl}.include?(code)
  %tr
    %td= link_to image_tag("currencies/#{code}_logo.png", :alt => t("currencies.#{code}.name"), :title => t("currencies.#{code}.name")), t("currencies.#{code}.link"), :target => "_blank", :title => t("currencies.#{code}.name")
    %td= code.upcase
    %td.account-balance{ :title => exact_balance(balance, code) }
      %div{ :class => color_for_balance(balance) }
        #{sign_for_balance(balance)} #{number_to_currency(balance, :unit => "", :precision => 8)}

        - if code == "btc" and unconfirmed_btc > 0
          %br
          %span.unconfirmed{ :title => t(:balance_unconfirmed) }
            + #{number_to_currency(unconfirmed_btc, :unit => "", :precision => 8)}

app/views/accounts/_lr_sci_form.html.erb
<p name="lr">
  <%= t(".click_for_lr_html", :action => "$('#add_lr').submit();") %>
</p>

<form id="add_lr" action="https://sci.libertyreserve.com/en" method="POST">
  <input type="hidden" name="lr_acc" value="<%= BitcoinBank::LibertyReserve['account'] %>" />

  <input type="hidden" name="lr_store" value="<%= BitcoinBank::LibertyReserve['store'] %>" />
  <input type="hidden" name="lr_merchant_ref" value="<%= @current_user.id %>" />
  <input type="hidden" name="lr_comments" value="Transfer funds to account <%= @current_user.name %>" />

  <input type="hidden" name="lr_success_url" value="<%= BitcoinBank::LibertyReserve['success_url'] %>" />
  <input type="hidden" name="lr_success_url_method" value="GET" />

  <input type="hidden" name="lr_fail_url" value="<%= BitcoinBank::LibertyReserve['fail_url'] %>" />
  <input type="hidden" name="lr_fail_url_method" value="GET" />

  <input type="hidden" name="lr_status_url" value="<%= BitcoinBank::LibertyReserve['status_url'] %>" />
  <input type="hidden" name="lr_status_url_method" value="POST" />

  <input type="hidden" name="account_id" value="<%= @current_user.id %>" />
</form>

app/views/accounts/_px_sci_form.html.erb
<form id="pecunix-sci-form" action="https://pri.pecunix.com/money.refined" method="post">
  <input type="hidden" name="PAYEE_ACCOUNT" value="<%= config["account"] %>" />
  <input name="PAYMENT_AMOUNT" value="<%= amount %>" />

  <input type="hidden" name="PAYMENT_URL" value="<%= config["payment_url"] %>" />
  <input type="hidden" name="PAYMENT_URL_METHOD" value="GET" />

  <input type="hidden" name="NOPAYMENT_URL" value="<%= config["no_payment_url"] %>" />
  <input type="hidden" name="NOPAYMENT_URL_METHOD" value="GET" />

  <input type="hidden" name="STATUS_URL" value="<%= config["status_url"] %>" />
  <input type="hidden" name="STATUS_TYPE" value="FORM" />

  <input type="hidden" name="INPUT_HASH" value="<%= hash %>" />

  <input type="hidden" name="PAYMENT_UNITS" value="GAU" />
  <input type="hidden" name="WHO_PAYS_FEES" value="PAYEE" />
  <input type="hidden" name="PAYMENT_ID" value="<%= payment_id %>" />

  <input type="hidden" name="SUGGESTED_MEMO" value="Transfer funds to account <%= @current_user.name %>" />
</form>

app/views/accounts/deposit.html.haml
%h1= t(".bitcoins.title")

%div{:style => "float:left; width: 50%" }
  %div{:style => "line-height: 30pt;" }
    %p
      %strong= t(".bitcoins.address") + ":"
      = link_to @current_user.bitcoin_address, "bitcoin:#{@current_user.bitcoin_address}"
    %p
      %strong= t(".bitcoins.conf_rqd") + ":"
      = Transfer::MIN_BTC_CONFIRMATIONS
      = t(".bitcoins.conf_rqd_unit")
    %p
      %strong= t(".bitcoins.conf_time") + ":"
      = Transfer::MIN_BTC_CONFIRMATIONS * 10
      = t(".bitcoins.conf_time_unit")
  %p
    = t(".bitcoins.add_info_html", :tx_address => "http://blockchain.info/address/#{@current_user.bitcoin_address}")

%div{:style => "float:left" }
  = image_tag(qrcode_image_path(current_user.bitcoin_address), :size => "120x120")
%div{:style => "clear:both;" }
%h1= t(".deposit_eur_title")
%p= t(".deposit_eur_body_html")

%div#bank-info
  - if (@bic && @iban && @account_holder)
    %table
      %tr
        %th= t(".comment")
        %td= current_user.name
      %tr
        %th= t(".account_holder")
        %td.account-holder= @account_holder
      %tr
        %th
        %td.account-holder-address= @account_holder_address
      
      %tr
        %td{ :colspan => 2 } &nbsp;
        
      %tr
        %th= t(".ag")
        %td= @ag
      %tr
        %th= t(".cc")
        %td= @cc
      %tr
        %th= t(".cnpj")
        %td= @cnpj
      %tr
        %th= t(".bank")
        %td.bank= @bank
      %tr
        %th
        %td.bank-address= @bank_address
      -#    %tr
-#      %th= t(".bic")
-#      %td= @bic
-#    %tr
-#      %th= t(".iban")
-#      %td= @iban

  - else
    %p#unavailable= t(".not_available")

-# %h1= t(".other_options")

-# %h2 Deposit CAD
-# %p= link_to "View instructions", "/s/cad_operations"

-# %h2 Deposit INR
-# %p= link_to "View instructions", "/s/inr_operations"

-# %h2= t(".deposit_lr_title")
-# %p= render(:partial => 'lr_sci_form')

-# %h2= t(".deposit_pgau_title")
-# %p= t(".deposit_pgau_body_html")

%br

-# = form_tag pecunix_deposit_form_account_path, :method => :get, :remote => true do
-#   .form-field
-#     = label_tag :amount, t(".pgau_amount")
-#     = text_field_tag :amount, nil

-#   .form-field
-#     = submit_tag t(".deposit_pgau"), :class => "submit"
  
-# #pecunix-sci-form-container.hidden

app/views/accounts/pecunix_deposit_form.js.erb
$("div#pecunix-sci-form-container").html("<%= escape_javascript(render(:partial => "accounts/px_sci_form", :locals => { :config => @config, :hash => @hash, :amount => @amount, :payment_id => @payment_id })).html_safe %>");
$("#pecunix-sci-form").submit();

app/views/accounts/show.html.haml
.creation-link
  = link_to("#{image_tag("add.gif", :alt => t(".add_funds"), :title => t(".add_funds"))} #{t(".add_funds")}".html_safe, new_account_deposit_path)

%h1= t :account_balance_title

%table#account-balances.default
  %tr
    %th
    %th= t :currency
    %th= t :balance  

  - @balances.keys.sort.each do |code|
    - unless %w{UNCONFIRMED_BTC ADDRESS}.include?(code) 
      = render :partial => 'accounts/balance_row', :locals => { :code => code.downcase, :balance => @balances[code], :unconfirmed_btc => @balances['UNCONFIRMED_BTC'] }